swagger: "2.0"
info:
  title: Reusable components in the health care domain
  version: ${project.version}
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths: {}
definitions:
  {}